baseURL: "https://www.enricopesce.it/"
title: Enrico Pesce's blog
theme: PaperMod
googleAnalytics: "G-N6VMEVB66C"
copyright: "Enrico Pesce"
enableRobotsTXT: false
languageCode: "en-US"
defaultContentLanguage: "en"

sitemap:
  changefreq: Weekly
  filename: sitemap.xml
  priority: 0.5

disableKinds:
- taxonomy
- term

permalinks:
  posts: "/:slug/"

pagination:
  disableAliases: false
  pagerSize: 20
  path: page

params:
  Description: "Enrico, a Cloud Solution Engineer, uses technology to transform challenges into opportunities with cloud services."
  author: "Enrico Pesce"

  schema:
    publisherType: "Person"
    sameAs:
      - "https://www.linkedin.com/in/enricopesce/"
      - "https://github.com/enricopesce"

  keywords:
    - "cloud solutions"
    - "oracle cloud infrastructure"
    - "oci"
    - "serverless"
    - "kubernetes"
    - "devops"
    - "cloud engineering"
    - "enrico pesce"

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  editPost:
    URL: "https://github.com/enricopesce/blog/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true
  cover:
    hiddenInList: false
    hiddenInSingle: false
  favicon: "/img/favicon.ico"
  env: production

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: archives
      name: Archives
      url: archives/
      weight: 10
    - identifier: about
      name: About
      url: about/
      weight: 20


      