baseURL: "https://www.enricopesce.it/"
title: Enrico Pesce's blog
theme: PaperMod
googleAnalytics: "G-N6VMEVB66C"
copyright: "Enrico Pesce"
enableRobotsTXT: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml

permalinks:
  posts: "/:slug/"

params:
  Description: "Enrico, a Cloud Solution Engineer, uses technology to transform challenges into opportunities with cloud services."
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  editPost:
    URL: "https://github.com/enricopesce/blog/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true
  cover:
    hiddenInList: false
    hiddenInSingle: false
  favicon: "/img/favicon.ico"
  env: production

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories

menu:
  main:
    - identifier: categories
      name: Categories
      url: categories/
      weight: 10
    - identifier: archives
      name: Archives
      url: archives/
      weight: 20
    - identifier: about
      name: About
      url: about/
      weight: 30